import argparse
import json
import re
from collections import Counter
from pathlib import Path

import pandas as pd

DATALAKE_DIR = Path(__file__).resolve().parents[2]

REQUIRED_GROUPS = [
    "test_q1_2024_baseline_no_memory",
    "test_q1_2024_2022_memory_weekly_learning",
    "test_q1_2024_weekly_learning_only",
]


REQUIRED_SCRIPTS = [
    DATALAKE_DIR / "run_memo_tournament.py",
    DATALAKE_DIR / "builders" / "memo_weekly_lesson_manager.py",
    DATALAKE_DIR / "builders" / "memo_portfolio_evaluator.py",
    DATALAKE_DIR / "tools" / "contracts" / "test_memo_portfolio_evaluation_contract.py",
    DATALAKE_DIR / "tools" / "contracts" / "test_memo_q1_real_artifact_contract.py",
]


MOCK_TRAJECTORY_ID_RE = re.compile(r"^traj_\d+$", re.IGNORECASE)
MOCK_REPORT_MARKERS = [
    "generated by mock",
    "mock pipeline",
    "dummy",
    "placeholder",
]


class Contract:
    def __init__(self):
        self.passed = 0
        self.failed = 0

    def check(self, name, condition, details=""):
        if condition:
            print(f"[PASS] {name}{' - ' + details if details else ''}")
            self.passed += 1
        else:
            print(f"[FAIL] {name}{' - ' + details if details else ''}")
            self.failed += 1

    def finish(self):
        print("\n--- Summary ---")
        print(f"PASS={self.passed} FAIL={self.failed}")
        if self.failed:
            raise SystemExit(1)


def load_jsonl(path: Path):
    if not path.exists():
        return []
    rows = []
    with path.open("r", encoding="utf-8-sig") as f:
        for line_no, line in enumerate(f, start=1):
            line = line.strip()
            if not line:
                continue
            try:
                rows.append(json.loads(line))
            except json.JSONDecodeError as exc:
                raise AssertionError(f"Invalid JSONL at {path}:{line_no}: {exc}") from exc
    return rows


def has_arg(script_path: Path, arg_name: str):
    if not script_path.exists():
        return False
    text = script_path.read_text(encoding="utf-8", errors="ignore")
    return arg_name in text


def read_parquet_dataset(path: Path):
    if not path.exists():
        return pd.DataFrame()
    try:
        return pd.read_parquet(path)
    except Exception as exc:
        raise AssertionError(f"Failed to read parquet dataset {path}: {exc}") from exc


def check_price_coverage(contract, data_dir: Path, symbols, start_date, end_date):
    price_candidates = [
        data_dir / "features" / "price_daily",
        data_dir / "normalized" / "price_daily",
    ]
    price_path = next((p for p in price_candidates if p.exists()), price_candidates[0])
    df = read_parquet_dataset(price_path)
    contract.check("Q1 price_daily exists and is readable", not df.empty, str(price_path))
    if df.empty:
        return

    date_col = "known_time" if "known_time" in df.columns else "trade_date"
    contract.check("price_daily has a date column", date_col in df.columns, date_col)
    contract.check("price_daily has instrument_id", "instrument_id" in df.columns)
    if date_col not in df.columns or "instrument_id" not in df.columns:
        return

    df["_date"] = pd.to_datetime(df[date_col].astype(str).str[:10], errors="coerce")
    start = pd.to_datetime(start_date)
    end = pd.to_datetime(end_date)
    eval_df = df[(df["_date"] >= start) & (df["_date"] <= end)]
    counts = eval_df.groupby("instrument_id").size().to_dict()
    for symbol in symbols:
        count = int(counts.get(symbol, 0))
        contract.check(f"price_daily covers {symbol}", count >= 50, f"{count} rows in eval window")


def check_snapshot_or_inputs(contract, data_dir: Path, symbols, start_date, end_date):
    snapshot_path = data_dir / "snapshots" / "agent_input_snapshots" / "snapshots.jsonl"
    input_path = data_dir / "memo_adaptation" / "materialized_inputs" / "inputs_ctx_paper_aligned_v1.jsonl"
    rows = load_jsonl(input_path) if input_path.exists() else load_jsonl(snapshot_path)
    source = input_path if input_path.exists() else snapshot_path
    contract.check("Q1 snapshots/materialized inputs exist", len(rows) > 0, str(source))
    if not rows:
        return

    start = start_date
    end = end_date
    filtered = []
    for row in rows:
        symbol = row.get("symbol") or row.get("instrument_id")
        analysis_time = str(row.get("analysis_time") or row.get("snapshot_time") or row.get("trade_date") or "")
        date = analysis_time[:10]
        if symbol in symbols and start <= date <= end:
            filtered.append(row)
    symbol_counts = Counter(row.get("symbol") or row.get("instrument_id") for row in filtered)
    for symbol in symbols:
        contract.check(f"Q1 context rows cover {symbol}", symbol_counts[symbol] >= 50, f"{symbol_counts[symbol]} rows")


def check_existing_mock_outputs(contract, data_dir: Path, tournament_id: str, allow_existing_outputs: bool):
    memo_root = data_dir / "memo_adaptation"
    traj_path = memo_root / "trajectories" / "workflow_trajectories.jsonl"
    rows = [r for r in load_jsonl(traj_path) if r.get("tournament_id") == tournament_id]

    if allow_existing_outputs:
        contract.check("existing Q1 outputs allowed by flag", True)
        return

    contract.check(
        "no existing Q1 trajectories before real run",
        len(rows) == 0,
        f"{len(rows)} existing rows at {traj_path}",
    )

    mock_ids = [r.get("trajectory_id") for r in rows if MOCK_TRAJECTORY_ID_RE.match(str(r.get("trajectory_id", "")))]
    contract.check(
        "no mock-style existing trajectory IDs",
        len(mock_ids) == 0,
        f"mock_id_count={len(mock_ids)} sample={mock_ids[:5]}",
    )

    portfolio_dir = memo_root / "portfolio_evaluation"
    existing_metrics = list(portfolio_dir.glob("**/portfolio_metrics.jsonl")) if portfolio_dir.exists() else []
    contract.check(
        "no existing portfolio evaluation outputs before real run",
        len(existing_metrics) == 0,
        f"{len(existing_metrics)} metric files under {portfolio_dir}",
    )

    report_candidates = [
        DATALAKE_DIR / "reports" / "q1_2024_portfolio_evaluation_report.md",
        portfolio_dir / "summary_report.md",
    ]
    report_text = ""
    for path in report_candidates:
        if path.exists():
            report_text += "\n" + path.read_text(encoding="utf-8", errors="ignore").lower()
    has_mock_report = any(marker in report_text for marker in MOCK_REPORT_MARKERS)
    contract.check("no mock Q1 report present", not has_mock_report)


def main():
    parser = argparse.ArgumentParser(
        description="Pre-run readiness contract for real Q1-2024 MeMo portfolio experiments."
    )
    parser.add_argument("--data-dir", default=str(DATALAKE_DIR / "data_test_2024_q1"))
    parser.add_argument("--train-data-dir", default=str(DATALAKE_DIR / "data"))
    parser.add_argument("--tournament-id", default="tour_2024_q1_eval")
    parser.add_argument("--start-date", default="2024-01-02")
    parser.add_argument("--end-date", default="2024-03-29")
    parser.add_argument("--symbols", nargs="+", default=["AAPL", "AMZN", "GOOGL"])
    parser.add_argument(
        "--seed-memory-bank-version",
        default="mb_2022_full_highvar_trueskill_socialproxy_llm_v1",
    )
    parser.add_argument(
        "--allow-existing-outputs",
        action="store_true",
        help="Allow existing Q1 trajectory/evaluation outputs. Use only when intentionally resuming a real run.",
    )
    args = parser.parse_args()

    contract = Contract()
    data_dir = Path(args.data_dir)
    train_data_dir = Path(args.train_data_dir)

    print("Q1 pre-run readiness contract tests")
    print(f"data_dir={data_dir}")
    print(f"train_data_dir={train_data_dir}")
    print(f"tournament_id={args.tournament_id}")

    for script in REQUIRED_SCRIPTS:
        path = Path(script)
        contract.check(f"required script exists: {script}", path.exists())

    runner = DATALAKE_DIR / "run_memo_tournament.py"
    weekly = DATALAKE_DIR / "builders" / "memo_weekly_lesson_manager.py"
    evaluator = DATALAKE_DIR / "builders" / "memo_portfolio_evaluator.py"

    contract.check("runner supports --data-dir for test isolation", has_arg(runner, "--data-dir"))
    contract.check("weekly lesson manager supports --data-dir", has_arg(weekly, "--data-dir"))
    contract.check("portfolio evaluator supports --data-dir", has_arg(evaluator, "--data-dir"))
    contract.check("runner supports --resume", has_arg(runner, "--resume"))
    contract.check("runner supports --comparison-group", has_arg(runner, "--comparison-group"))
    contract.check("runner supports --memory-bank-version", has_arg(runner, "--memory-bank-version"))

    check_price_coverage(contract, data_dir, args.symbols, args.start_date, args.end_date)
    check_snapshot_or_inputs(contract, data_dir, args.symbols, args.start_date, args.end_date)

    train_memory_path = train_data_dir / "memo_adaptation" / "memory_bank" / "memo_memory_bank.jsonl"
    train_memories = load_jsonl(train_memory_path)
    seed_count = sum(1 for row in train_memories if row.get("memory_bank_version") == args.seed_memory_bank_version)
    contract.check(
        "2022 seed memory bank exists in train data",
        seed_count > 0,
        f"{seed_count} rows for {args.seed_memory_bank_version}",
    )

    test_memory_path = data_dir / "memo_adaptation" / "memory_bank" / "memo_memory_bank.jsonl"
    if test_memory_path.exists():
        test_memories = load_jsonl(test_memory_path)
        arm_c_2022 = [
            row.get("memory_id")
            for row in test_memories
            if row.get("memory_bank_version") == "mb_q1_2024_weekly_only_v1"
            and "2022" in json.dumps(row, ensure_ascii=False)
        ]
        contract.check(
            "Arm C existing memory has no 2022 contamination",
            len(arm_c_2022) == 0,
            f"violations={arm_c_2022[:5]}",
        )
    else:
        contract.check("test memory bank path can be created later", True, str(test_memory_path))

    check_existing_mock_outputs(contract, data_dir, args.tournament_id, args.allow_existing_outputs)

    print("\nExpected real-run comparison groups:")
    for group in REQUIRED_GROUPS:
        print(f"- {group}")

    contract.finish()


if __name__ == "__main__":
    main()
